[package]
name = "fuzz_debug"
version = "0.1.0"
authors = ["markschl <markschl19@gmail.com>"]
edition = "2018"

[dependencies]
exprtk_rs = { path = "../.." }
approx = "0.4.0"
arbitrary = { version = "0.4", features = ["derive"] }

[workspace]
members = ["."]
